[tool.basedpyright]
extraPaths = [
    "/nix/store/xg3k1858dwc80vpsnmsx29wra9p0ja8s-python3-3.13.7-env/lib/python3.13/site-packages"
]

# python3 - << EOF
# import sys; print("\n".join(sys.path))
# EOF
